import '../models/product.dart';
import '../models/artisan.dart';
import '../models/category.dart';

class DummyData {
  static List<Product> get products => [
    Product(
      id: '1',
      name: 'Kanchipuram Silk Saree',
      description: 'Handwoven pure silk saree with traditional gold zari work from Kanchipuram, Tamil Nadu. This exquisite piece showcases centuries-old weaving techniques.',
      price: 15000,
      images: [
        'assets/images/tamilnadu_tanjore.webp',
        'https://example.com/saree2.jpg',
      ],
      category: 'Handloom',
      state: 'Tamil Nadu',
      artisanId: 'artisan1',
      artisanName: 'Meera Devi',
      rating: 4.8,
      reviewCount: 127,
      tags: ['Silk', 'Traditional', 'Wedding', 'Zari Work'],
      isAvailable: true,
      stockCount: 5,
      heritage: 'Kanchipuram silk weaving is a 400-year-old tradition',
      specifications: {
        'Material': 'Pure Mulberry Silk',
        'Thread Count': '1200',
        'Weight': '650 grams',
        'Length': '6.5 meters',
      },
    ),
    Product(
      id: '2',
      name: 'Blue Pottery Vase Set',
      description: 'Exquisite set of traditional Rajasthani blue pottery vases with intricate white floral and paisley patterns. Handcrafted using ancient techniques with quartz stone powder and natural glazes. Perfect for home decoration and gifting.',
      price: 4500,
      images: [
        'assets/images/blue_pottery_rajasthan.webp',
        'https://example.com/pottery2.jpg',
      ],
      category: 'Pottery',
      state: 'Rajasthan',
      artisanId: 'artisan2',
      artisanName: 'Ramesh Kumhar',
      rating: 4.8,
      reviewCount: 127,
      tags: ['Blue Pottery', 'Decorative', 'Handmade', 'Jaipur', 'Vase Set', 'Traditional'],
      isAvailable: true,
      stockCount: 8,
      heritage: 'Blue pottery tradition brought to Jaipur in 14th century by Mongol artisans',
      specifications: {
        'Set of': '3 Vases (Large, Medium, Small)',
        'Heights': 'Large: 30cm, Medium: 25cm, Small: 20cm',
        'Material': 'Quartz Stone Powder & Natural Glazes',
        'Technique': 'Hand-painted with traditional patterns',
        'Pattern': 'White floral and paisley motifs on blue base',
        'Finish': 'Gold rim accents',
        'Origin': 'Jaipur, Rajasthan',
      },
    ),
    Product(
      id: '3',
      name: 'Madhubani Painting',
      description: 'Authentic Madhubani painting depicting Hindu deities and nature motifs on handmade paper using natural pigments.',
      price: 3500,
      images: [
        'https://example.com/madhubani1.jpg',
        'https://example.com/madhubani2.jpg',
      ],
      category: 'Paintings',
      state: 'Bihar',
      artisanId: 'artisan3',
      artisanName: 'Ganga Devi',
      rating: 4.9,
      reviewCount: 156,
      tags: ['Folk Art', 'Natural Pigments', 'Religious', 'Mithila'],
      isAvailable: true,
      stockCount: 8,
      heritage: 'Madhubani art dates back to 7th century BCE',
      specifications: {
        'Size': '40x30 cm',
        'Paper': 'Handmade',
        'Colors': 'Natural Pigments',
        'Style': 'Bharni',
      },
    ),
    Product(
      id: '4',
      name: 'Terracotta Horse',
      description: 'Traditional terracotta horse figurine from Bankura, West Bengal. Handcrafted by skilled artisans using local clay.',
      price: 1200,
      images: [
        'https://example.com/horse1.jpg',
        'https://example.com/horse2.jpg',
      ],
      category: 'Terracotta',
      state: 'West Bengal',
      artisanId: 'artisan4',
      artisanName: 'Bishnu Das',
      rating: 4.4,
      reviewCount: 73,
      tags: ['Terracotta', 'Bankura', 'Folk Art', 'Decorative'],
      isAvailable: true,
      stockCount: 15,
      heritage: 'Bankura terracotta craft is over 1000 years old',
      specifications: {
        'Height': '20 cm',
        'Material': 'Local Clay',
        'Finish': 'Natural',
        'Weight': '800 grams',
      },
    ),
    Product(
      id: '5',
      name: 'Rajasthani Bandhani Dupatta',
      description: 'Exquisite traditional Bandhani (tie-dye) dupatta from Jaipur, featuring intricate geometric patterns in vibrant royal colors. Each piece is handcrafted using ancient tie-dye techniques passed down through generations of Rajasthani artisans.',
      price: 2800,
      images: [
        'assets/images/rajasthan_bandhani.webp',
        'https://example.com/bandhani2.jpg',
      ],
      category: 'Handloom',
      state: 'Rajasthan',
      artisanId: 'artisan6',
      artisanName: 'Kamal Singh Rathore',
      rating: 4.7,
      reviewCount: 156,
      tags: ['Bandhani', 'Tie-Dye', 'Traditional', 'Jaipur', 'Royal', 'Dupatta'],
      isAvailable: true,
      stockCount: 12,
      heritage: 'Bandhani art originated in Rajasthan over 5000 years ago during Indus Valley civilization',
      specifications: {
        'Length': '2.5 meters',
        'Width': '1 meter',
        'Material': 'Pure Cotton with Silk Border',
        'Pattern': 'Traditional Leheriya with Dots',
        'Colors': 'Royal Blue & Gold',
        'Technique': 'Hand-tied and Natural Dyed',
        'Care': 'Dry Clean Recommended',
      },
    ),
    Product(
      id: '6',
      name: 'Rajasthani Meenakari Jewelry Box',
      description: 'Royal Meenakari jewelry box with intricate enamel work in traditional Rajasthani style. Features hand-painted floral motifs with gold and silver accents on brass base. Perfect for storing precious jewelry and gifts.',
      price: 3200,
      images: [
        'assets/images/rajasthan_meenakari.webp',
        'https://example.com/meenakari2.jpg',
      ],
      category: 'Metalwork',
      state: 'Rajasthan',
      artisanId: 'artisan7',
      artisanName: 'Mohan Lal Soni',
      rating: 4.9,
      reviewCount: 89,
      tags: ['Meenakari', 'Enamel Work', 'Jewelry Box', 'Royal', 'Brass', 'Handcrafted'],
      isAvailable: true,
      stockCount: 6,
      heritage: 'Meenakari art brought to Rajasthan by Persian craftsmen in 16th century Mughal era',
      specifications: {
        'Size': '20cm x 15cm x 8cm',
        'Material': 'Brass with Enamel Work',
        'Compartments': '6 Velvet-lined sections',
        'Design': 'Traditional Floral Motifs',
        'Colors': 'Multi-colored Enamel with Gold accents',
        'Weight': '1.2 kg',
        'Finish': 'Antique Gold with Mirror Inside Lid',
      },
    ),
    Product(
      id: '7',
      name: 'Rajasthani Block Print Bedsheet Set',
      description: 'Luxurious cotton bedsheet set with authentic Rajasthani block printing from Sanganer. Features traditional paisley and floral motifs hand-printed using natural dyes. Complete with matching pillow covers.',
      price: 1800,
      images: [
        'assets/images/rajasthan_blockprint.jpg',
        'https://example.com/blockprint2.jpg',
      ],
      category: 'Handloom',
      state: 'Rajasthan',
      artisanId: 'artisan8',
      artisanName: 'Gopal Chand Chippa',
      rating: 4.6,
      reviewCount: 234,
      tags: ['Block Print', 'Sanganer', 'Cotton', 'Natural Dyes', 'Bedsheet', 'Traditional'],
      isAvailable: true,
      stockCount: 18,
      heritage: 'Sanganer block printing tradition dates back to 12th century',
      specifications: {
        'Set Includes': '1 Double Bedsheet + 2 Pillow Covers',
        'Size': 'Double Bed (90" x 108")',
        'Material': '100% Pure Cotton',
        'Thread Count': '200 TC',
        'Print': 'Hand Block Printed',
        'Dyes': 'Natural Vegetable Dyes',
        'Pattern': 'Traditional Paisley with Floral Border',
        'Colors': 'Indigo Blue on White Base',
      },
    ),
    Product(
      id: '8',
      name: 'Rajasthani Leather Mojari Shoes',
      description: 'Authentic handcrafted Rajasthani Mojari shoes with traditional embroidery and mirror work. Made from genuine leather by skilled cobblers of Jodhpur, featuring pointed toe design and intricate Rajasthani patterns.',
      price: 2400,
      images: [
        'assets/images/rajasthan_mojari.webp',
        'https://example.com/mojari2.jpg',
      ],
      category: 'Footwear',
      state: 'Rajasthan',
      artisanId: 'artisan9',
      artisanName: 'Kishore Suthar',
      rating: 4.5,
      reviewCount: 142,
      tags: ['Mojari', 'Leather', 'Handcrafted', 'Jodhpur', 'Embroidery', 'Traditional'],
      isAvailable: true,
      stockCount: 25,
      heritage: 'Mojari craftsmanship originated in Rajasthan during medieval times for royal families',
      specifications: {
        'Material': 'Genuine Camel Leather',
        'Sole': 'Leather with Rubber Grip',
        'Embroidery': 'Silk Thread with Mirror Work',
        'Colors': 'Maroon with Gold Embroidery',
        'Sizes Available': 'UK 6-11',
        'Style': 'Traditional Pointed Toe',
        'Comfort': 'Cushioned Insole',
        'Origin': 'Jodhpur, Rajasthan',
      },
    ),
    Product(
      id: '9',
      name: 'Bamboo Basket Set',
      description: 'Eco-friendly bamboo basket set handwoven by Assamese artisans using traditional techniques passed down through generations.',
      price: 800,
      images: [
        'https://example.com/bamboo1.jpg',
        'https://example.com/bamboo2.jpg',
      ],
      category: 'Bamboo Crafts',
      state: 'Assam',
      artisanId: 'artisan5',
      artisanName: 'Ruma Sharma',
      rating: 4.5,
      reviewCount: 94,
      tags: ['Eco-friendly', 'Sustainable', 'Storage', 'Handwoven'],
      isAvailable: true,
      stockCount: 20,
      heritage: 'Assamese bamboo craft tradition spans centuries',
      specifications: {
        'Set Size': '3 pieces',
        'Material': '100% Bamboo',
        'Largest Size': '30x20 cm',
        'Treatment': 'Natural',
      },
    ),
    Product(
      id: '10',
      name: 'Traditional Tanjore Painting',
      description: 'Authentic Tanjore painting featuring Lord Krishna with intricate gold foil work and precious stone embellishments. Handcrafted by master artists from Thanjavur using traditional techniques dating back to the Maratha period.',
      price: 8500,
      images: [
        'assets/images/tamilnadu_bharatanatyam.jpg',
        'https://example.com/tanjore2.jpg',
      ],
      category: 'Paintings',
      state: 'Tamil Nadu',
      artisanId: 'artisan10',
      artisanName: 'Ravi Shankar',
      rating: 4.9,
      reviewCount: 167,
      tags: ['Tanjore Painting', 'Gold Foil', 'Traditional', 'Religious', 'Krishna', 'Thanjavur'],
      isAvailable: true,
      stockCount: 4,
      heritage: 'Tanjore painting originated in Thanjavur during 16th century Maratha rule',
      specifications: {
        'Size': '45cm x 35cm',
        'Frame': 'Traditional Teak Wood with Gold Polish',
        'Medium': 'Natural Pigments on Canvas',
        'Gold Work': '22K Gold Foil',
        'Gems': 'Semi-precious stones and pearls',
        'Theme': 'Lord Krishna with Radha',
        'Technique': 'Traditional Gesso and Gold leaf application',
        'Origin': 'Thanjavur, Tamil Nadu',
      },
    ),
    Product(
      id: '11',
      name: 'Bharatanatyam Dance Costume Set',
      description: 'Complete traditional Bharatanatyam dance costume with intricate temple jewelry and accessories. Handcrafted in rich silk with traditional South Indian motifs, gold zari work, and authentic dance jewelry set.',
      price: 12000,
      images: [
        'assets/images/tamilnadu_nataraja.jpg',
        'https://example.com/bharatanatyam2.jpg',
      ],
      category: 'Handloom',
      state: 'Tamil Nadu',
      artisanId: 'artisan11',
      artisanName: 'Lakshmi Priya',
      rating: 4.8,
      reviewCount: 89,
      tags: ['Bharatanatyam', 'Dance Costume', 'Silk', 'Temple Jewelry', 'Traditional', 'Performance'],
      isAvailable: true,
      stockCount: 3,
      heritage: 'Bharatanatyam costume tradition rooted in ancient Tamil temple dance culture',
      specifications: {
        'Costume Includes': 'Blouse, Dhoti-style Pants, Dupatta',
        'Material': 'Pure Kanchipuram Silk',
        'Color': 'Royal Maroon with Gold Zari',
        'Jewelry Set': '15-piece Temple Jewelry in Antique Gold',
        'Accessories': 'Hair Flowers, Ankle Bells, Armlets',
        'Embellishments': 'Traditional Gold Thread Work',
        'Sizes Available': 'Custom Tailored (S, M, L, XL)',
        'Care': 'Dry Clean Only',
      },
    ),
    Product(
      id: '12',
      name: 'Bronze Nataraja Statue',
      description: 'Exquisite handcrafted bronze Nataraja statue representing Lord Shiva in cosmic dance form. Created using traditional lost-wax casting technique by master sculptors from Swamimalai, following ancient Chola dynasty artistic traditions.',
      price: 15000,
      images: [
        'assets/images/tamilnadu_cotton_saree.webp',
        'https://example.com/nataraja2.jpg',
      ],
      category: 'Metalwork',
      state: 'Tamil Nadu',
      artisanId: 'artisan12',
      artisanName: 'Murugan Sthapati',
      rating: 4.9,
      reviewCount: 156,
      tags: ['Bronze', 'Nataraja', 'Shiva', 'Sculpture', 'Traditional', 'Swamimalai', 'Chola Art'],
      isAvailable: true,
      stockCount: 2,
      heritage: 'Bronze casting tradition from Chola period, UNESCO recognized craftsmanship',
      specifications: {
        'Height': '30 cm (12 inches)',
        'Material': 'Panchaloha Bronze (5-metal alloy)',
        'Weight': '3.5 kg',
        'Technique': 'Lost-wax (Cire Perdue) casting method',
        'Finish': 'Traditional Patina with Antique Look',
        'Base': 'Lotus Pedestal with Sanskrit Inscriptions',
        'Symbolism': 'Cosmic Dance of Creation and Destruction',
        'Craftsman': 'Sthapati Community Master Sculptor',
        'Origin': 'Swamimalai, Tamil Nadu',
      },
    ),
    Product(
      id: '13',
      name: 'Kanchipuram Cotton Saree',
      description: 'Pure handloom cotton saree from Kanchipuram with traditional temple border designs. Woven with organic cotton threads and natural dyes, featuring classic Tamil motifs and comfortable daily wear styling.',
      price: 3500,
      images: [
        'assets/images/tamilnadu_cotton_saree_new.webp',
        'https://example.com/cotton_saree2.jpg',
      ],
      category: 'Handloom',
      state: 'Tamil Nadu',
      artisanId: 'artisan13',
      artisanName: 'Kamala Devi',
      rating: 4.7,
      reviewCount: 298,
      tags: ['Cotton Saree', 'Kanchipuram', 'Handloom', 'Temple Border', 'Natural Dyes', 'Daily Wear'],
      isAvailable: true,
      stockCount: 15,
      heritage: 'Kanchipuram cotton weaving tradition complements the famous silk sarees',
      specifications: {
        'Length': '6.5 meters with 80cm Blouse Piece',
        'Material': '100% Organic Handloom Cotton',
        'Weave': 'Traditional Temple Weave',
        'Border': 'Contrast Temple Border with Zari accents',
        'Colors': 'Peacock Blue with Gold Border',
        'Motifs': 'Traditional Tamil Temple Designs',
        'Thread Count': '80s Count Cotton',
        'Care': 'Hand Wash with Mild Detergent',
      },
    ),
    Product(
      id: '14',
      name: 'Tamil Temple Jewelry Set',
      description: 'Authentic temple jewelry set in traditional South Indian style with intricate goddess motifs, antique gold finish, and ruby-emerald stone work. Perfect for classical dance, weddings, and festive occasions.',
      price: 4500,
      images: [
        'assets/images/tamilnadu_temple_jewelry.jpg',
        'https://example.com/temple_jewelry2.jpg',
      ],
      category: 'Traditional Jewelry',
      state: 'Tamil Nadu',
      artisanId: 'artisan14',
      artisanName: 'Swarna Raj',
      rating: 4.8,
      reviewCount: 134,
      tags: ['Temple Jewelry', 'South Indian', 'Antique Gold', 'Ruby Emerald', 'Goddess Motifs', 'Classical'],
      isAvailable: true,
      stockCount: 8,
      heritage: 'Temple jewelry tradition inspired by Chola and Pandya dynasty ornaments',
      specifications: {
        'Set Includes': 'Necklace, Earrings, Maang Tikka, Armlets, Waist Chain',
        'Metal': 'Antique Gold Plated Brass',
        'Stones': 'Ruby, Emerald, and Pearl replicas',
        'Design': 'Traditional Lakshmi and Peacock Motifs',
        'Weight': '850 grams (complete set)',
        'Finish': 'Oxidized Antique Gold Look',
        'Technique': 'Temple Art Embossing and Stone Setting',
        'Occasions': 'Weddings, Classical Dance, Festivals',
      },
    ),
    Product(
      id: '15',
      name: 'Pochampally Ikat Silk Saree',
      description: 'Exquisite handwoven Pochampally Ikat silk saree with traditional geometric patterns. Created using the ancient resist-dyeing technique where threads are tied and dyed before weaving, resulting in unique blurred-edge designs characteristic of this UNESCO recognized craft.',
      price: 6500,
      images: [
        'assets/images/telangana_pochampally.jpeg',
        'https://example.com/pochampally2.jpg',
      ],
      category: 'Handloom',
      state: 'Telangana',
      artisanId: 'artisan15',
      artisanName: 'Padma Reddy',
      rating: 4.8,
      reviewCount: 178,
      tags: ['Pochampally', 'Ikat', 'Silk Saree', 'UNESCO', 'Handwoven', 'Geometric Patterns'],
      isAvailable: true,
      stockCount: 7,
      heritage: 'Pochampally Ikat is a UNESCO Intangible Cultural Heritage craft dating back to 18th century',
      specifications: {
        'Length': '6.5 meters with 80cm Blouse Piece',
        'Material': 'Pure Mulberry Silk',
        'Technique': 'Traditional Ikat Resist-Dyeing',
        'Pattern': 'Geometric Diamond and Square Motifs',
        'Colors': 'Deep Purple with Gold Ikat Borders',
        'Thread Count': '250 GSM',
        'Weave Time': '15-20 days per saree',
        'Origin': 'Pochampally, Telangana',
        'Care': 'Dry Clean Recommended',
      },
    ),
    Product(
      id: '16',
      name: 'Bidriware Decorative Vase',
      description: 'Authentic Bidriware vase with intricate silver inlay work on blackened metal. This traditional Telangana craft features delicate floral patterns and geometric designs hand-engraved and inlaid with pure silver, showcasing the 600-year-old artistry.',
      price: 4200,
      images: [
        'assets/images/telangana_bidriware.jpeg',
        'https://example.com/bidriware2.jpg',
      ],
      category: 'Metalwork',
      state: 'Telangana',
      artisanId: 'artisan16',
      artisanName: 'Mohammed Yusuf',
      rating: 4.7,
      reviewCount: 124,
      tags: ['Bidriware', 'Silver Inlay', 'Metal Craft', 'Decorative', 'Traditional', 'Hyderabad'],
      isAvailable: true,
      stockCount: 5,
      heritage: 'Bidriware originated in Bidar (now Karnataka) and flourished in Hyderabad during Bahmani Sultanate',
      specifications: {
        'Height': '25 cm',
        'Material': 'Zinc-Copper Alloy with Silver Inlay',
        'Technique': 'Hand Engraving and Silver Wire Inlay',
        'Finish': 'Traditional Black Oxidation',
        'Pattern': 'Persian Floral Motifs with Geometric Borders',
        'Silver Content': 'Pure 925 Silver Inlay Work',
        'Weight': '1.8 kg',
        'Style': 'Hyderabadi Bidriware',
        'Origin': 'Hyderabad, Telangana',
      },
    ),
    Product(
      id: '17',
      name: 'Nirmal Wooden Toys Set',
      description: 'Colorful hand-painted wooden toys from Nirmal featuring traditional Telangana folk art. Each piece is carved from sustainable wood and painted with natural colors, depicting mythological characters and animals in vibrant traditional style.',
      price: 1800,
      images: [
        'assets/images/telangana_nirmal_toys.webp',
        'https://example.com/nirmal2.jpg',
      ],
      category: 'Woodwork',
      state: 'Telangana',
      artisanId: 'artisan17',
      artisanName: 'Ravi Kumar Sharma',
      rating: 4.6,
      reviewCount: 156,
      tags: ['Nirmal Art', 'Wooden Toys', 'Folk Art', 'Hand Painted', 'Traditional', 'Natural Colors'],
      isAvailable: true,
      stockCount: 12,
      heritage: 'Nirmal art originated during Kakatiya dynasty and was patronized by Nizams of Hyderabad',
      specifications: {
        'Set Includes': '8 Wooden Toys (Animals & Mythological Figures)',
        'Material': 'Sustainable Mango Wood',
        'Size Range': '5cm to 15cm height',
        'Paint': 'Natural Mineral and Vegetable Colors',
        'Technique': 'Hand Carving and Traditional Painting',
        'Themes': 'Krishna, Ganesha, Elephant, Horse, Peacock',
        'Finish': 'Natural Lacquer Coating',
        'Age Group': 'Suitable for 3+ years',
        'Origin': 'Nirmal, Telangana',
      },
    ),
    Product(
      id: '18',
      name: 'Kalamkari Wall Hanging',
      description: 'Traditional Kalamkari wall hanging featuring mythological scenes painted with natural dyes on handwoven cotton fabric. Created using the ancient pen-work technique with intricate detailing of Hindu epics and floral motifs.',
      price: 3200,
      images: [
        'assets/images/telangana_craft_4.jpg',
        'https://example.com/kalamkari2.jpg',
      ],
      category: 'Paintings',
      state: 'Telangana',
      artisanId: 'artisan18',
      artisanName: 'Srinivas Rao',
      rating: 4.8,
      reviewCount: 134,
      tags: ['Kalamkari', 'Natural Dyes', 'Wall Hanging', 'Mythological', 'Hand Painted', 'Traditional'],
      isAvailable: true,
      stockCount: 6,
      heritage: 'Kalamkari art dates back to 3000 years, flourished under Golconda Sultanate',
      specifications: {
        'Size': '90cm x 60cm',
        'Material': 'Handwoven Cotton Fabric',
        'Colors': 'Natural Vegetable and Mineral Dyes',
        'Technique': 'Traditional Pen-work (Kalam) Method',
        'Theme': 'Ramayana Epic Scenes with Floral Borders',
        'Dyes Used': 'Indigo, Madder, Pomegranate, Iron',
        'Process Time': '20-25 days per piece',
        'Frame': 'Traditional Bamboo Rod for Hanging',
        'Origin': 'Srikalahasti Style, Telangana',
      },
    ),
    Product(
      id: '19',
      name: 'Telangana Dhokra Metal Figurine',
      description: 'Authentic Dhokra brass figurine depicting traditional Telangana tribal art. Handcrafted using the ancient lost-wax casting technique, featuring intricate tribal patterns and representing the rich cultural heritage of Telangana tribal communities.',
      price: 2800,
      images: [
        'assets/images/telangana_craft_5.webp',
        'https://example.com/dhokra2.jpg',
      ],
      category: 'Metalwork',
      state: 'Telangana',
      artisanId: 'artisan19',
      artisanName: 'Lakshmi Tribal',
      rating: 4.7,
      reviewCount: 98,
      tags: ['Dhokra', 'Brass', 'Tribal Art', 'Lost Wax Casting', 'Traditional', 'Figurine'],
      isAvailable: true,
      stockCount: 9,
      heritage: 'Dhokra craft practiced by tribal communities for over 4000 years',
      specifications: {
        'Height': '20 cm',
        'Material': 'Brass using Lost-Wax Casting',
        'Design': 'Traditional Tribal Dancer with Ornaments',
        'Technique': '4000-year-old Cire Perdue Method',
        'Finish': 'Natural Brass Patina',
        'Weight': '850 grams',
        'Tribe': 'Created by Lambadi Tribal Artisans',
        'Symbolism': 'Celebration and Cultural Identity',
        'Origin': 'Tribal Areas of Telangana',
      },
    ),
  ];

  static List<Artisan> get artisans => [
    Artisan(
      id: 'artisan1',
      name: 'Meera Devi',
      profileImage: 'https://example.com/meera.jpg',
      coverImage: 'https://example.com/kanchipuram_bg.jpg',
      state: 'Tamil Nadu',
      city: 'Kanchipuram',
      bio: 'Master weaver specializing in Kanchipuram silk sarees',
      story: 'Born into a family of traditional weavers, Meera has been practicing the art for over 25 years. She learned from her grandmother and is now teaching the craft to young women in her village.',
      specializations: ['Silk Weaving', 'Zari Work', 'Traditional Patterns'],
      rating: 4.8,
      reviewCount: 340,
      yearsOfExperience: 25,
      heritage: 'Fourth generation weaver from Kanchipuram',
      awards: ['National Award for Handloom Excellence', 'UNESCO Recognition'],
      productIds: ['1'],
      socialLinks: {'instagram': '@meera_silk_weaver'},
      isVerified: true,
      joinedDate: DateTime(2020, 1, 15),
    ),
    Artisan(
      id: 'artisan2',
      name: 'Ramesh Kumhar',
      profileImage: 'https://example.com/ramesh.jpg',
      coverImage: 'https://example.com/jaipur_bg.jpg',
      state: 'Rajasthan',
      city: 'Jaipur',
      bio: 'Master blue pottery artisan specializing in traditional Jaipur ceramics',
      story: 'Ramesh comes from a family that has been making blue pottery for five generations. He learned the intricate art of painting floral and paisley patterns from his grandfather. His workshop preserves the authentic Mongol techniques while creating contemporary designs that blend tradition with modern aesthetics.',
      specializations: ['Blue Pottery', 'Ceramic Glazing', 'Traditional Patterns', 'Decorative Vases'],
      rating: 4.8,
      reviewCount: 320,
      yearsOfExperience: 32,
      heritage: 'Fifth generation blue pottery artist, custodian of ancient Mongol techniques',
      awards: ['Rajasthan State Award for Handicrafts', 'National Craft Council Recognition', 'UNESCO Intangible Heritage Award'],
      productIds: ['2'],
      socialLinks: {'facebook': 'ramesh.bluepottery', 'instagram': '@jaipurbluepottery'},
      isVerified: true,
      joinedDate: DateTime(2019, 8, 20),
    ),
    Artisan(
      id: 'artisan3',
      name: 'Ganga Devi',
      profileImage: 'https://example.com/ganga.jpg',
      coverImage: 'https://example.com/madhubani_bg.jpg',
      state: 'Bihar',
      city: 'Madhubani',
      bio: 'Renowned Madhubani painter and Padma Shri awardee',
      story: 'Ganga Devi is one of the most celebrated Madhubani artists. She has exhibited her work internationally and has been instrumental in bringing global recognition to this folk art.',
      specializations: ['Madhubani Painting', 'Folk Art', 'Natural Pigments'],
      rating: 4.9,
      reviewCount: 520,
      yearsOfExperience: 40,
      heritage: 'Lifelong practitioner of Mithila art tradition',
      awards: ['Padma Shri', 'National Award for Art', 'International Folk Art Award'],
      productIds: ['3'],
      socialLinks: {'website': 'gangadevi-madhubani.com'},
      isVerified: true,
      joinedDate: DateTime(2018, 5, 10),
    ),
    Artisan(
      id: 'artisan6',
      name: 'Kamal Singh Rathore',
      profileImage: 'https://example.com/kamal.jpg',
      coverImage: 'https://example.com/bandhani_bg.jpg',
      state: 'Rajasthan',
      city: 'Jaipur',
      bio: 'Master Bandhani artisan specializing in traditional tie-dye techniques',
      story: 'Kamal Singh belongs to the royal Rathore family of traditional dyers. His family has been practicing Bandhani for 8 generations, serving Maharajas and preserving the ancient art. He combines traditional methods with contemporary designs.',
      specializations: ['Bandhani Tie-Dye', 'Natural Dyeing', 'Leheriya Patterns', 'Traditional Textiles'],
      rating: 4.7,
      reviewCount: 178,
      yearsOfExperience: 28,
      heritage: 'Eighth generation Bandhani artist from royal dyer family',
      awards: ['Rajasthan Gaurav Award', 'National Handicrafts Award'],
      productIds: ['5'],
      socialLinks: {'instagram': '@royal_bandhani_jaipur'},
      isVerified: true,
      joinedDate: DateTime(2020, 3, 12),
    ),
    Artisan(
      id: 'artisan7',
      name: 'Mohan Lal Soni',
      profileImage: 'https://example.com/mohan.jpg',
      coverImage: 'https://example.com/meenakari_bg.jpg',
      state: 'Rajasthan',
      city: 'Jaipur',
      bio: 'Master Meenakari craftsman specializing in enamel work and traditional jewelry',
      story: 'Mohan Lal comes from the famous Soni community of Jaipur, known for their exceptional skills in Meenakari. His workshop in the old city has been creating exquisite pieces for royal families and collectors worldwide for over 30 years.',
      specializations: ['Meenakari Enamel Work', 'Jewelry Making', 'Traditional Patterns', 'Brass Craftsmanship'],
      rating: 4.9,
      reviewCount: 145,
      yearsOfExperience: 35,
      heritage: 'Fifth generation Meenakari artist, descendant of royal court craftsmen',
      awards: ['Shilp Guru Award', 'UNESCO Excellence in Handicrafts', 'National Merit Certificate'],
      productIds: ['6'],
      socialLinks: {'facebook': 'soni.meenakari.jaipur'},
      isVerified: true,
      joinedDate: DateTime(2019, 11, 8),
    ),
    Artisan(
      id: 'artisan8',
      name: 'Gopal Chand Chippa',
      profileImage: 'https://example.com/gopal.jpg',
      coverImage: 'https://example.com/sanganer_bg.jpg',
      state: 'Rajasthan',
      city: 'Sanganer',
      bio: 'Traditional block printer from the famous Chippa community of Sanganer',
      story: 'Gopal Chand belongs to the historic Chippa community, the traditional block printers of Sanganer. His family workshop has been creating beautiful textiles for over 200 years, using hand-carved wooden blocks and natural dyes.',
      specializations: ['Block Printing', 'Natural Dyeing', 'Traditional Patterns', 'Textile Design'],
      rating: 4.6,
      reviewCount: 267,
      yearsOfExperience: 22,
      heritage: 'Seventh generation block printer from Chippa community',
      awards: ['State Award for Block Printing', 'Export Excellence Award'],
      productIds: ['7'],
      socialLinks: {'website': 'sanganer-prints.com'},
      isVerified: true,
      joinedDate: DateTime(2020, 1, 25),
    ),
    Artisan(
      id: 'artisan9',
      name: 'Kishore Suthar',
      profileImage: 'https://example.com/kishore.jpg',
      coverImage: 'https://example.com/jodhpur_bg.jpg',
      state: 'Rajasthan',
      city: 'Jodhpur',
      bio: 'Master cobbler specializing in traditional Rajasthani Mojari footwear',
      story: 'Kishore Suthar represents the fourth generation of traditional cobblers in Jodhpur. His family has been crafting Mojari shoes for the royal families of Marwar. He combines ancient techniques with modern comfort to create authentic footwear.',
      specializations: ['Mojari Craftsmanship', 'Leather Work', 'Traditional Embroidery', 'Royal Footwear'],
      rating: 4.5,
      reviewCount: 198,
      yearsOfExperience: 26,
      heritage: 'Fourth generation Mojari craftsman from Suthar community',
      awards: ['Jodhpur Heritage Craft Award', 'Excellence in Traditional Footwear'],
      productIds: ['8'],
      socialLinks: {'instagram': '@jodhpur_mojari_house'},
      isVerified: true,
      joinedDate: DateTime(2019, 7, 14),
    ),
    Artisan(
      id: 'artisan10',
      name: 'Ravi Shankar',
      profileImage: 'https://example.com/ravi.jpg',
      coverImage: 'https://example.com/thanjavur_bg.jpg',
      state: 'Tamil Nadu',
      city: 'Thanjavur',
      bio: 'Master Tanjore painter specializing in traditional gold foil artwork',
      story: 'Ravi Shankar belongs to a family of traditional Tanjore painters who have been creating these masterpieces for six generations. He learned the intricate art of gold leaf application and gem setting from his grandfather. His workshop continues the authentic techniques of the Maratha period.',
      specializations: ['Tanjore Painting', 'Gold Foil Work', 'Religious Art', 'Traditional Techniques'],
      rating: 4.9,
      reviewCount: 189,
      yearsOfExperience: 24,
      heritage: 'Sixth generation Tanjore artist, preserving Maratha period techniques',
      awards: ['State Award for Traditional Arts', 'UNESCO Heritage Craft Recognition'],
      productIds: ['10'],
      socialLinks: {'facebook': 'tanjore.art.ravi', 'instagram': '@thanjavur_paintings'},
      isVerified: true,
      joinedDate: DateTime(2020, 2, 18),
    ),
    Artisan(
      id: 'artisan11',
      name: 'Lakshmi Priya',
      profileImage: 'https://example.com/lakshmi.jpg',
      coverImage: 'https://example.com/bharatanatyam_bg.jpg',
      state: 'Tamil Nadu',
      city: 'Chennai',
      bio: 'Traditional costume designer and Bharatanatyam dancer specializing in authentic dance attire',
      story: 'Lakshmi Priya is a renowned Bharatanatyam performer who transitioned to creating authentic dance costumes. She combines her deep understanding of the dance form with traditional tailoring skills to create costumes that enhance the dancer\'s performance.',
      specializations: ['Bharatanatyam Costumes', 'Temple Jewelry', 'Silk Tailoring', 'Traditional Embroidery'],
      rating: 4.8,
      reviewCount: 156,
      yearsOfExperience: 18,
      heritage: 'Classical dancer turned costume designer, preserving authentic traditions',
      awards: ['Excellence in Traditional Costume Design', 'Cultural Heritage Award'],
      productIds: ['11'],
      socialLinks: {'website': 'bharatanatyam-costumes.com', 'instagram': '@classical_costumes_chennai'},
      isVerified: true,
      joinedDate: DateTime(2019, 9, 5),
    ),
    Artisan(
      id: 'artisan12',
      name: 'Murugan Sthapati',
      profileImage: 'https://example.com/murugan.jpg',
      coverImage: 'https://example.com/swamimalai_bg.jpg',
      state: 'Tamil Nadu',
      city: 'Swamimalai',
      bio: 'Master bronze sculptor from the traditional Sthapati community',
      story: 'Murugan Sthapati represents the ancient tradition of bronze casting that dates back to the Chola period. His family has been creating bronze sculptures for temples and collectors for over 400 years. He is a UNESCO recognized master craftsman.',
      specializations: ['Bronze Casting', 'Lost-wax Technique', 'Panchaloha Alloy', 'Temple Sculptures'],
      rating: 4.9,
      reviewCount: 234,
      yearsOfExperience: 32,
      heritage: 'Tenth generation Sthapati, UNESCO recognized master bronze sculptor',
      awards: ['UNESCO Excellence Award', 'Padma Shri Recommendation', 'National Heritage Craft Award'],
      productIds: ['12'],
      socialLinks: {'website': 'swamimalai-bronzes.org'},
      isVerified: true,
      joinedDate: DateTime(2018, 11, 12),
    ),
    Artisan(
      id: 'artisan13',
      name: 'Kamala Devi',
      profileImage: 'https://example.com/kamala.jpg',
      coverImage: 'https://example.com/kanchipuram_cotton_bg.jpg',
      state: 'Tamil Nadu',
      city: 'Kanchipuram',
      bio: 'Expert cotton saree weaver specializing in temple border designs',
      story: 'Kamala Devi learned cotton weaving alongside silk weaving in Kanchipuram. She focuses on creating comfortable, elegant cotton sarees that carry the same traditional motifs as the famous silk versions, making them accessible for daily wear.',
      specializations: ['Cotton Handloom', 'Temple Border Weaving', 'Natural Dyeing', 'Traditional Motifs'],
      rating: 4.7,
      reviewCount: 267,
      yearsOfExperience: 19,
      heritage: 'Third generation cotton weaver from Kanchipuram weaving community',
      awards: ['State Handloom Excellence Award', 'Organic Cotton Pioneer Award'],
      productIds: ['13'],
      socialLinks: {'instagram': '@kanchipuram_cotton_sarees'},
      isVerified: true,
      joinedDate: DateTime(2020, 6, 8),
    ),
    Artisan(
      id: 'artisan14',
      name: 'Swarna Raj',
      profileImage: 'https://example.com/swarna.jpg',
      coverImage: 'https://example.com/temple_jewelry_bg.jpg',
      state: 'Tamil Nadu',
      city: 'Chennai',
      bio: 'Traditional temple jewelry craftsman specializing in South Indian ornaments',
      story: 'Swarna Raj comes from a family of traditional jewelers who have been creating temple jewelry for classical dancers and brides for generations. His designs are inspired by ancient temple sculptures and traditional South Indian motifs.',
      specializations: ['Temple Jewelry Design', 'Antique Gold Work', 'Stone Setting', 'Traditional Motifs'],
      rating: 4.8,
      reviewCount: 178,
      yearsOfExperience: 25,
      heritage: 'Fourth generation temple jewelry craftsman',
      awards: ['Traditional Jewelry Excellence Award', 'Heritage Craft Recognition'],
      productIds: ['14'],
      socialLinks: {'facebook': 'swarna.temple.jewelry', 'instagram': '@south_indian_temple_jewelry'},
      isVerified: true,
      joinedDate: DateTime(2019, 4, 22),
    ),
    Artisan(
      id: 'artisan15',
      name: 'Padma Reddy',
      profileImage: 'https://example.com/padma.jpg',
      coverImage: 'https://example.com/pochampally_bg.jpg',
      state: 'Telangana',
      city: 'Pochampally',
      bio: 'Master Ikat weaver specializing in UNESCO recognized Pochampally craft',
      story: 'Padma Reddy belongs to a family that has been weaving Pochampally Ikat for five generations. She learned the complex tie-dye technique from her grandmother and is now training young women in her village. Her work has been exhibited internationally as part of UNESCO cultural heritage programs.',
      specializations: ['Ikat Weaving', 'Resist Dyeing', 'Geometric Patterns', 'Silk Weaving'],
      rating: 4.8,
      reviewCount: 234,
      yearsOfExperience: 28,
      heritage: 'Fifth generation Pochampally Ikat weaver, UNESCO craft custodian',
      awards: ['UNESCO Heritage Craft Award', 'National Handloom Excellence', 'Telangana State Award'],
      productIds: ['15'],
      socialLinks: {'instagram': '@pochampally_ikat_original', 'facebook': 'padma.pochampally.weaves'},
      isVerified: true,
      joinedDate: DateTime(2019, 12, 3),
    ),
    Artisan(
      id: 'artisan16',
      name: 'Mohammed Yusuf',
      profileImage: 'https://example.com/yusuf.jpg',
      coverImage: 'https://example.com/bidriware_bg.jpg',
      state: 'Telangana',
      city: 'Hyderabad',
      bio: 'Master Bidriware artisan specializing in silver inlay metalwork',
      story: 'Mohammed Yusuf represents the seventh generation of Bidriware craftsmen in his family. His ancestors migrated from Bidar to Hyderabad during the Bahmani period. He has mastered the intricate art of silver inlay work and has been featured in national exhibitions.',
      specializations: ['Bidriware', 'Silver Inlay', 'Metal Engraving', 'Traditional Patterns'],
      rating: 4.7,
      reviewCount: 189,
      yearsOfExperience: 32,
      heritage: 'Seventh generation Bidriware craftsman from Bahmani era lineage',
      awards: ['National Award for Metal Craft', 'Hyderabad Heritage Award', 'Excellence in Traditional Arts'],
      productIds: ['16'],
      socialLinks: {'website': 'hyderabad-bidriware.com', 'instagram': '@authentic_bidriware'},
      isVerified: true,
      joinedDate: DateTime(2018, 8, 15),
    ),
    Artisan(
      id: 'artisan17',
      name: 'Ravi Kumar Sharma',
      profileImage: 'https://example.com/ravi_nirmal.jpg',
      coverImage: 'https://example.com/nirmal_bg.jpg',
      state: 'Telangana',
      city: 'Nirmal',
      bio: 'Traditional Nirmal art painter and wooden toy craftsman',
      story: 'Ravi Kumar learned Nirmal painting from the legendary masters of this art form. His family workshop in Nirmal town has been creating colorful wooden toys and paintings for four generations. He combines traditional themes with child-safe materials and techniques.',
      specializations: ['Nirmal Painting', 'Wood Carving', 'Natural Colors', 'Folk Art'],
      rating: 4.6,
      reviewCount: 167,
      yearsOfExperience: 21,
      heritage: 'Fourth generation Nirmal artist, preserving Kakatiya era traditions',
      awards: ['Telangana Folk Art Award', 'Best Traditional Toy Maker', 'Heritage Craft Excellence'],
      productIds: ['17'],
      socialLinks: {'facebook': 'nirmal.art.ravi', 'instagram': '@nirmal_wooden_crafts'},
      isVerified: true,
      joinedDate: DateTime(2020, 5, 18),
    ),
    Artisan(
      id: 'artisan18',
      name: 'Srinivas Rao',
      profileImage: 'https://example.com/srinivas.jpg',
      coverImage: 'https://example.com/kalamkari_bg.jpg',
      state: 'Telangana',
      city: 'Hyderabad',
      bio: 'Master Kalamkari artist specializing in mythological narrative paintings',
      story: 'Srinivas Rao learned Kalamkari from the traditional artisans of Srikalahasti and Machilipatnam. He has dedicated his life to preserving this ancient art form and has created numerous masterpieces depicting Hindu epics using only natural dyes and traditional techniques.',
      specializations: ['Kalamkari Painting', 'Natural Dye Preparation', 'Mythological Themes', 'Pen Work Technique'],
      rating: 4.8,
      reviewCount: 156,
      yearsOfExperience: 26,
      heritage: 'Master of ancient Kalamkari tradition, natural dye expert',
      awards: ['National Award for Kalamkari Art', 'UNESCO Cultural Heritage Recognition', 'Master Craftsman Award'],
      productIds: ['18'],
      socialLinks: {'website': 'srinivas-kalamkari.org', 'instagram': '@traditional_kalamkari_art'},
      isVerified: true,
      joinedDate: DateTime(2019, 1, 8),
    ),
    Artisan(
      id: 'artisan19',
      name: 'Lakshmi Tribal',
      profileImage: 'https://example.com/lakshmi_tribal.jpg',
      coverImage: 'https://example.com/dhokra_tribal_bg.jpg',
      state: 'Telangana',
      city: 'Adilabad',
      bio: 'Tribal Dhokra artist from the Lambadi community specializing in traditional metal casting',
      story: 'Lakshmi represents the ancient tribal tradition of Dhokra metal casting that has been practiced by her community for centuries. She learned this craft from her elders and is now teaching young tribal women to preserve their cultural heritage and provide livelihood opportunities.',
      specializations: ['Dhokra Metal Casting', 'Lost Wax Technique', 'Tribal Art Motifs', 'Brass Work'],
      rating: 4.7,
      reviewCount: 123,
      yearsOfExperience: 18,
      heritage: 'Lambadi tribal artisan, keeper of 4000-year-old Dhokra tradition',
      awards: ['Tribal Art Excellence Award', 'Women Empowerment through Crafts', 'Heritage Preservation Award'],
      productIds: ['19'],
      socialLinks: {'instagram': '@tribal_dhokra_art'},
      isVerified: true,
      joinedDate: DateTime(2020, 9, 12),
    ),
  ];

  static List<Category> get categories => [
    Category(
      id: 'handloom',
      name: 'Handloom',
      description: 'Traditional handwoven textiles from across India',
      icon: '🧵',
      image: 'https://example.com/handloom_category.jpg',
      subCategories: ['Sarees', 'Dupattas', 'Fabrics', 'Scarves'],
      productCount: 1250,
      popularStates: ['Tamil Nadu', 'West Bengal', 'Odisha', 'Kerala'],
    ),
    Category(
      id: 'pottery',
      name: 'Pottery & Ceramics',
      description: 'Handcrafted pottery and ceramic items',
      icon: '🏺',
      image: 'https://example.com/pottery_category.jpg',
      subCategories: ['Vases', 'Bowls', 'Decorative Items', 'Utility Items'],
      productCount: 890,
      popularStates: ['Rajasthan', 'Gujarat', 'Uttar Pradesh', 'Manipur'],
    ),
    Category(
      id: 'jewelry',
      name: 'Traditional Jewelry',
      description: 'Authentic Indian jewelry and ornaments',
      icon: '💍',
      image: 'https://example.com/jewelry_category.jpg',
      subCategories: ['Necklaces', 'Earrings', 'Bangles', 'Rings'],
      productCount: 2100,
      popularStates: ['Rajasthan', 'Gujarat', 'Odisha', 'Tamil Nadu'],
    ),
    Category(
      id: 'paintings',
      name: 'Folk Paintings',
      description: 'Traditional Indian paintings and folk art',
      icon: '🎨',
      image: 'https://example.com/paintings_category.jpg',
      subCategories: ['Madhubani', 'Warli', 'Pattachitra', 'Tanjore'],
      productCount: 670,
      popularStates: ['Bihar', 'Maharashtra', 'Odisha', 'Tamil Nadu'],
    ),
    Category(
      id: 'woodwork',
      name: 'Woodwork',
      description: 'Carved wooden items and furniture',
      icon: '🪵',
      image: 'https://example.com/woodwork_category.jpg',
      subCategories: ['Sculptures', 'Furniture', 'Decorative Items', 'Toys'],
      productCount: 1100,
      popularStates: ['Karnataka', 'Kashmir', 'Rajasthan', 'Kerala'],
    ),
    Category(
      id: 'metalwork',
      name: 'Metalwork',
      description: 'Traditional metal crafts and jewelry',
      icon: '⚒️',
      image: 'https://example.com/metalwork_category.jpg',
      subCategories: ['Meenakari', 'Brass Items', 'Jewelry Boxes', 'Decorative Items'],
      productCount: 420,
      popularStates: ['Rajasthan', 'Uttar Pradesh', 'Punjab', 'Gujarat'],
    ),
    Category(
      id: 'footwear',
      name: 'Traditional Footwear',
      description: 'Authentic handcrafted traditional shoes',
      icon: '👡',
      image: 'https://example.com/footwear_category.jpg',
      subCategories: ['Mojari', 'Kolhapuri Chappal', 'Juttis', 'Paduka'],
      productCount: 280,
      popularStates: ['Rajasthan', 'Maharashtra', 'Punjab', 'Haryana'],
    ),
    Category(
      id: 'bamboo',
      name: 'Bamboo Crafts',
      description: 'Eco-friendly bamboo products',
      icon: '🎋',
      image: 'https://example.com/bamboo_category.jpg',
      subCategories: ['Baskets', 'Furniture', 'Home Decor', 'Utilities'],
      productCount: 540,
      popularStates: ['Assam', 'Tripura', 'Manipur', 'West Bengal'],
    ),
  ];

  static List<StateTheme> get stateThemes => [
    StateTheme(
      state: 'rajasthan',
      name: 'Rajasthan',
      backgroundImage: 'https://example.com/rajasthan_bg.jpg',
      colors: ['#FF6B35', '#F7931E', '#FFD23F'],
      specialCraft: 'Blue Pottery & Textiles',
      description: 'Land of vibrant colors and royal crafts',
      heritage: 'Desert kingdom with rich artistic traditions',
    ),
    StateTheme(
      state: 'tamilnadu',
      name: 'Tamil Nadu',
      backgroundImage: 'https://example.com/tamilnadu_bg.jpg',
      colors: ['#8B4513', '#DAA520', '#FF8C00'],
      specialCraft: 'Silk Weaving & Bronze',
      description: 'Ancient land of temples and textiles',
      heritage: 'Dravidian culture with temple arts',
    ),
    StateTheme(
      state: 'westbengal',
      name: 'West Bengal',
      backgroundImage: 'https://example.com/westbengal_bg.jpg',
      colors: ['#CD853F', '#DEB887', '#F4A460'],
      specialCraft: 'Terracotta & Textiles',
      description: 'Cultural hub of eastern India',
      heritage: 'Rich tradition in arts and crafts',
    ),
    StateTheme(
      state: 'kerala',
      name: 'Kerala',
      backgroundImage: 'https://example.com/kerala_bg.jpg',
      colors: ['#228B22', '#32CD32', '#90EE90'],
      specialCraft: 'Coconut & Spice Crafts',
      description: 'God\'s own country with natural crafts',
      heritage: 'Backwater culture and natural materials',
    ),
    StateTheme(
      state: 'gujarat',
      name: 'Gujarat',
      backgroundImage: 'https://example.com/gujarat_bg.jpg',
      colors: ['#FF1493', '#FFB6C1', '#FFC0CB'],
      specialCraft: 'Embroidery & Textiles',
      description: 'Land of vibrant embroidery and crafts',
      heritage: 'Trading heritage with rich textile traditions',
    ),
    StateTheme(
      state: 'telangana',
      name: 'Telangana',
      backgroundImage: 'https://example.com/telangana_bg.jpg',
      colors: ['#8A2BE2', '#9370DB', '#BA55D3'],
      specialCraft: 'Ikat & Bidriware',
      description: 'Land of Nizams and royal crafts',
      heritage: 'Rich heritage from Kakatiya to Nizam dynasties',
    ),
  ];
}