import '../models/product.dart';
import '../models/artisan.dart';
import '../models/category.dart';

class DummyData {
  static List<Product> get products => [
    Product(
      id: '1',
      name: 'Kanchipuram Silk Saree',
      description: 'Handwoven pure silk saree with traditional gold zari work from Kanchipuram, Tamil Nadu. This exquisite piece showcases centuries-old weaving techniques.',
      price: 15000,
      images: [
        'https://example.com/saree1.jpg',
        'https://example.com/saree2.jpg',
      ],
      category: 'Handloom',
      state: 'Tamil Nadu',
      artisanId: 'artisan1',
      artisanName: 'Meera Devi',
      rating: 4.8,
      reviewCount: 127,
      tags: ['Silk', 'Traditional', 'Wedding', 'Zari Work'],
      isAvailable: true,
      stockCount: 5,
      heritage: 'Kanchipuram silk weaving is a 400-year-old tradition',
      specifications: {
        'Material': 'Pure Mulberry Silk',
        'Thread Count': '1200',
        'Weight': '650 grams',
        'Length': '6.5 meters',
      },
    ),
    Product(
      id: '2',
      name: 'Blue Pottery Vase',
      description: 'Traditional Rajasthani blue pottery vase with intricate floral patterns. Made using the ancient technique with quartz stone powder.',
      price: 2500,
      images: [
        'https://example.com/pottery1.jpg',
        'https://example.com/pottery2.jpg',
      ],
      category: 'Pottery',
      state: 'Rajasthan',
      artisanId: 'artisan2',
      artisanName: 'Ramesh Kumhar',
      rating: 4.6,
      reviewCount: 89,
      tags: ['Blue Pottery', 'Decorative', 'Handmade', 'Jaipur'],
      isAvailable: true,
      stockCount: 12,
      heritage: 'Blue pottery tradition brought to Jaipur in 14th century',
      specifications: {
        'Height': '25 cm',
        'Diameter': '15 cm',
        'Material': 'Quartz Stone Powder',
        'Technique': 'Hand-painted',
      },
    ),
    Product(
      id: '3',
      name: 'Madhubani Painting',
      description: 'Authentic Madhubani painting depicting Hindu deities and nature motifs on handmade paper using natural pigments.',
      price: 3500,
      images: [
        'https://example.com/madhubani1.jpg',
        'https://example.com/madhubani2.jpg',
      ],
      category: 'Paintings',
      state: 'Bihar',
      artisanId: 'artisan3',
      artisanName: 'Ganga Devi',
      rating: 4.9,
      reviewCount: 156,
      tags: ['Folk Art', 'Natural Pigments', 'Religious', 'Mithila'],
      isAvailable: true,
      stockCount: 8,
      heritage: 'Madhubani art dates back to 7th century BCE',
      specifications: {
        'Size': '40x30 cm',
        'Paper': 'Handmade',
        'Colors': 'Natural Pigments',
        'Style': 'Bharni',
      },
    ),
    Product(
      id: '4',
      name: 'Terracotta Horse',
      description: 'Traditional terracotta horse figurine from Bankura, West Bengal. Handcrafted by skilled artisans using local clay.',
      price: 1200,
      images: [
        'https://example.com/horse1.jpg',
        'https://example.com/horse2.jpg',
      ],
      category: 'Terracotta',
      state: 'West Bengal',
      artisanId: 'artisan4',
      artisanName: 'Bishnu Das',
      rating: 4.4,
      reviewCount: 73,
      tags: ['Terracotta', 'Bankura', 'Folk Art', 'Decorative'],
      isAvailable: true,
      stockCount: 15,
      heritage: 'Bankura terracotta craft is over 1000 years old',
      specifications: {
        'Height': '20 cm',
        'Material': 'Local Clay',
        'Finish': 'Natural',
        'Weight': '800 grams',
      },
    ),
    Product(
      id: '5',
      name: 'Bamboo Basket Set',
      description: 'Eco-friendly bamboo basket set handwoven by Assamese artisans using traditional techniques passed down through generations.',
      price: 800,
      images: [
        'https://example.com/bamboo1.jpg',
        'https://example.com/bamboo2.jpg',
      ],
      category: 'Bamboo Crafts',
      state: 'Assam',
      artisanId: 'artisan5',
      artisanName: 'Ruma Sharma',
      rating: 4.5,
      reviewCount: 94,
      tags: ['Eco-friendly', 'Sustainable', 'Storage', 'Handwoven'],
      isAvailable: true,
      stockCount: 20,
      heritage: 'Assamese bamboo craft tradition spans centuries',
      specifications: {
        'Set Size': '3 pieces',
        'Material': '100% Bamboo',
        'Largest Size': '30x20 cm',
        'Treatment': 'Natural',
      },
    ),
  ];

  static List<Artisan> get artisans => [
    Artisan(
      id: 'artisan1',
      name: 'Meera Devi',
      profileImage: 'https://example.com/meera.jpg',
      coverImage: 'https://example.com/kanchipuram_bg.jpg',
      state: 'Tamil Nadu',
      city: 'Kanchipuram',
      bio: 'Master weaver specializing in Kanchipuram silk sarees',
      story: 'Born into a family of traditional weavers, Meera has been practicing the art for over 25 years. She learned from her grandmother and is now teaching the craft to young women in her village.',
      specializations: ['Silk Weaving', 'Zari Work', 'Traditional Patterns'],
      rating: 4.8,
      reviewCount: 340,
      yearsOfExperience: 25,
      heritage: 'Fourth generation weaver from Kanchipuram',
      awards: ['National Award for Handloom Excellence', 'UNESCO Recognition'],
      productIds: ['1'],
      socialLinks: {'instagram': '@meera_silk_weaver'},
      isVerified: true,
      joinedDate: DateTime(2020, 1, 15),
    ),
    Artisan(
      id: 'artisan2',
      name: 'Ramesh Kumhar',
      profileImage: 'https://example.com/ramesh.jpg',
      coverImage: 'https://example.com/jaipur_bg.jpg',
      state: 'Rajasthan',
      city: 'Jaipur',
      bio: 'Traditional blue pottery artisan from Jaipur',
      story: 'Ramesh comes from a family that has been making blue pottery for five generations. He revived the dying art form in the 1980s and now runs a workshop training young artists.',
      specializations: ['Blue Pottery', 'Ceramic Art', 'Traditional Glazing'],
      rating: 4.6,
      reviewCount: 280,
      yearsOfExperience: 30,
      heritage: 'Fifth generation blue pottery artist',
      awards: ['Rajasthan State Award', 'Craft Council Recognition'],
      productIds: ['2'],
      socialLinks: {'facebook': 'ramesh.bluepottery'},
      isVerified: true,
      joinedDate: DateTime(2019, 8, 20),
    ),
    Artisan(
      id: 'artisan3',
      name: 'Ganga Devi',
      profileImage: 'https://example.com/ganga.jpg',
      coverImage: 'https://example.com/madhubani_bg.jpg',
      state: 'Bihar',
      city: 'Madhubani',
      bio: 'Renowned Madhubani painter and Padma Shri awardee',
      story: 'Ganga Devi is one of the most celebrated Madhubani artists. She has exhibited her work internationally and has been instrumental in bringing global recognition to this folk art.',
      specializations: ['Madhubani Painting', 'Folk Art', 'Natural Pigments'],
      rating: 4.9,
      reviewCount: 520,
      yearsOfExperience: 40,
      heritage: 'Lifelong practitioner of Mithila art tradition',
      awards: ['Padma Shri', 'National Award for Art', 'International Folk Art Award'],
      productIds: ['3'],
      socialLinks: {'website': 'gangadevi-madhubani.com'},
      isVerified: true,
      joinedDate: DateTime(2018, 5, 10),
    ),
  ];

  static List<Category> get categories => [
    Category(
      id: 'handloom',
      name: 'Handloom',
      description: 'Traditional handwoven textiles from across India',
      icon: '🧵',
      image: 'https://example.com/handloom_category.jpg',
      subCategories: ['Sarees', 'Dupattas', 'Fabrics', 'Scarves'],
      productCount: 1250,
      popularStates: ['Tamil Nadu', 'West Bengal', 'Odisha', 'Kerala'],
    ),
    Category(
      id: 'pottery',
      name: 'Pottery & Ceramics',
      description: 'Handcrafted pottery and ceramic items',
      icon: '🏺',
      image: 'https://example.com/pottery_category.jpg',
      subCategories: ['Vases', 'Bowls', 'Decorative Items', 'Utility Items'],
      productCount: 890,
      popularStates: ['Rajasthan', 'Gujarat', 'Uttar Pradesh', 'Manipur'],
    ),
    Category(
      id: 'jewelry',
      name: 'Traditional Jewelry',
      description: 'Authentic Indian jewelry and ornaments',
      icon: '💍',
      image: 'https://example.com/jewelry_category.jpg',
      subCategories: ['Necklaces', 'Earrings', 'Bangles', 'Rings'],
      productCount: 2100,
      popularStates: ['Rajasthan', 'Gujarat', 'Odisha', 'Tamil Nadu'],
    ),
    Category(
      id: 'paintings',
      name: 'Folk Paintings',
      description: 'Traditional Indian paintings and folk art',
      icon: '🎨',
      image: 'https://example.com/paintings_category.jpg',
      subCategories: ['Madhubani', 'Warli', 'Pattachitra', 'Tanjore'],
      productCount: 670,
      popularStates: ['Bihar', 'Maharashtra', 'Odisha', 'Tamil Nadu'],
    ),
    Category(
      id: 'woodwork',
      name: 'Woodwork',
      description: 'Carved wooden items and furniture',
      icon: '🪵',
      image: 'https://example.com/woodwork_category.jpg',
      subCategories: ['Sculptures', 'Furniture', 'Decorative Items', 'Toys'],
      productCount: 1100,
      popularStates: ['Karnataka', 'Kashmir', 'Rajasthan', 'Kerala'],
    ),
    Category(
      id: 'bamboo',
      name: 'Bamboo Crafts',
      description: 'Eco-friendly bamboo products',
      icon: '🎋',
      image: 'https://example.com/bamboo_category.jpg',
      subCategories: ['Baskets', 'Furniture', 'Home Decor', 'Utilities'],
      productCount: 540,
      popularStates: ['Assam', 'Tripura', 'Manipur', 'West Bengal'],
    ),
  ];

  static List<StateTheme> get stateThemes => [
    StateTheme(
      state: 'rajasthan',
      name: 'Rajasthan',
      backgroundImage: 'https://example.com/rajasthan_bg.jpg',
      colors: ['#FF6B35', '#F7931E', '#FFD23F'],
      specialCraft: 'Blue Pottery & Textiles',
      description: 'Land of vibrant colors and royal crafts',
      heritage: 'Desert kingdom with rich artistic traditions',
    ),
    StateTheme(
      state: 'tamilnadu',
      name: 'Tamil Nadu',
      backgroundImage: 'https://example.com/tamilnadu_bg.jpg',
      colors: ['#8B4513', '#DAA520', '#FF8C00'],
      specialCraft: 'Silk Weaving & Bronze',
      description: 'Ancient land of temples and textiles',
      heritage: 'Dravidian culture with temple arts',
    ),
    StateTheme(
      state: 'westbengal',
      name: 'West Bengal',
      backgroundImage: 'https://example.com/westbengal_bg.jpg',
      colors: ['#CD853F', '#DEB887', '#F4A460'],
      specialCraft: 'Terracotta & Textiles',
      description: 'Cultural hub of eastern India',
      heritage: 'Rich tradition in arts and crafts',
    ),
    StateTheme(
      state: 'kerala',
      name: 'Kerala',
      backgroundImage: 'https://example.com/kerala_bg.jpg',
      colors: ['#228B22', '#32CD32', '#90EE90'],
      specialCraft: 'Coconut & Spice Crafts',
      description: 'God\'s own country with natural crafts',
      heritage: 'Backwater culture and natural materials',
    ),
    StateTheme(
      state: 'gujarat',
      name: 'Gujarat',
      backgroundImage: 'https://example.com/gujarat_bg.jpg',
      colors: ['#FF1493', '#FFB6C1', '#FFC0CB'],
      specialCraft: 'Embroidery & Textiles',
      description: 'Land of vibrant embroidery and crafts',
      heritage: 'Trading heritage with rich textile traditions',
    ),
  ];
}